### ISSUE TITLE
Case IN-sensitive Sort Of Installed

### ISSUE THREAD

**Issue by kloggy** [hacs/frontend#101]
Would it be possible to have the sort of installed items case insensitive?
This is how it is now,

![image](https://user-images.githubusercontent.com/38220016/79571974-0e439480-80b4-11ea-81a1-92066e6946ed.png)

I think for example 'auto-entities' should be (in my case) at the top of the.

Just a small request.

**Comment by ludeeus** [comment]
It is that, has been for a while.
![image](https://user-images.githubusercontent.com/15093472/79573651-42708280-80bf-11ea-8392-f9c591397dac.png)

**Comment by ludeeus** [comment]
I guess not... Just the stores...
This code is messy...

**Comment by ludeeus** [comment]
https://github.com/hacs/frontend/commit/b88f5e80d7340c8ab35f78eb511643d880b8ccbc fixed it
