### ISSUE TITLE
Slow loading components

### ISSUE THREAD

**Issue by tuga49** [hacs/frontend#102]
Hi,

I'm facing a "problem" on refreshing HA. I'm not sure if this is normal or not. But I think this is not normal because is very annoying and I wan't to confirm if I miss something or is normal do that. I'm on version 0.108.3 and HACS 0.24.0, setted up on yaml:
```
hacs:
  token: xxxxxxxx
  sidepanel_title: HACS
  sidepanel_icon: "mdi:alpha-c-box"
```
and added the following to resources:
```
# https://github.com/thomasloven/lovelace-card-mod
- url: /hacsfiles/lovelace-card-mod/card-mod.js
  type: module
# https://github.com/cbulock/lovelace-battery-entity
- url: /hacsfiles/lovelace-battery-entity/battery-entity.js
  type: module
# https://github.com/custom-cards/button-card
- url: /hacsfiles/button-card/button-card.js
  type: module
```
I've tried 3 different plugins: "Battery Entity Card", "button-card" and "card-mod".
What happen is if I apply any custom component, when I refresh page, it loads the page without the components and then after millisecons, loads the component, and it shows like a "flick". Without applying custom components, it dont do that. Please check the gifs bellow:
![recording1](https://user-images.githubusercontent.com/17064445/79585996-78663480-80c8-11ea-8dc3-213df511401b.gif)
![recording2](https://user-images.githubusercontent.com/17064445/79586003-7a2ff800-80c8-11ea-8d54-140da5c2f6e9.gif)

Now, this is how an enitty works without custom cards, see the difference:
![Recording-_5](https://user-images.githubusercontent.com/17064445/79586442-0510f280-80c9-11ea-8afa-6b3dc9400120.gif)

Also my Header make a flicks, and I have the original one... What is making this happen? or is that normal? thank's

**Comment by ludeeus** [comment]
Change all `/hacsfiles/` to `/local/community/` if that does not help it's normal.

**Comment by tuga49** [comment]
> Change all `/hacsfiles/` to `/local/community/` if that does not help it's normal.

Where is this located?
What I can see is MYIP/config/custom_components/hacs

I don't see /hacsfiles/ and /local/community/. What should I do?

**Comment by ludeeus** [comment]
Read your first post again, and you will see it 3 places ;)

**Comment by tuga49** [comment]
> Read your first post again, and you will see it 3 places ;)

this is a url. so you mean i do this is resources?:
```
# https://github.com/thomasloven/lovelace-card-mod
- url: /local/community/lovelace-card-mod/card-mod.js
  type: module
# https://github.com/cbulock/lovelace-battery-entity
- url: /local/community/lovelace-battery-entity/battery-entity.js
  type: module
# https://github.com/custom-cards/button-card
- url: /local/community//button-card/button-card.js
  type: module

is that what I sould do?
```

**Comment by ludeeus** [comment]
yes

**Comment by tuga49** [comment]
> yes

ok, I did that. It's the same think. So you think that is normal? it happens with you? i'm following some videos to start customize with custom components, and on videos it seems to don't happen using HACS

**Comment by ludeeus** [comment]
Then it's normal, and since you now are not using HACS, the "problem" is not from HACS.
I do not use Lovelace, but I probably have the same.

Try asking on the Home Assistant discord server, or the Home Assistant forum.

**Comment by tuga49** [comment]
> Then it's normal, and since you now are not using HACS, the "problem" is not from HACS.
> I do not use Lovelace, but I probably have the same.
> 
> Try asking on the Home Assistant discord server, or the Home Assistant forum.

ok, thanks for your help
