### ISSUE TITLE
Welcome to HACS! on every reboot

### ISSUE THREAD

**Issue by wifi75** [hacs/frontend#111]
hello I don't understand why, but every time I restart HA if I click on Hacs the welcome message always appears, I click several times it continues, and then it disappears, but if I restart it Ha shows up again. what can I do?

**Comment by ludeeus** [comment]
remove it from your YAML config

**Comment by wifi75** [comment]
sorry it what?

**Comment by ludeeus** [comment]
HACS

**Comment by wifi75** [comment]
Thank you! now it is ok!
