### ISSUE TITLE
Feature Request: Landing page is available updates, otherwise it shows installed

### ISSUE THREAD

**Issue by rpitera** [hacs/frontend#16]
I find that even (moreso?) with the experimental UI, I'm doing a lot of scrolling to check what needs to be updated.  With the grid view this is a little easier, but still seems inefficient.

What would be awesome is that if anything that HACS is tracking is in need of an update, instead INSTALLED being the landing page, the would be another tab that appears only when there are updates and provides a filtered list of just the things that require an update.  The existing INSTALLED tab as well as all the others would still be there, this new tab would simply appear as the first tab.

(EDIT: It should also comply with the hiding feature!  Same thing for the sensor alternative below.)

I guess an alternative to this would be a sensor that didn't just show the count, but provided a list of the names, installed versions and version available (even better, with the version available hyperlinking to the changelog).  Then you could quickly check the sensor in a Lovelace card.

I feel like I miss this kind of ability from the old Custom Updater days.  But I *do* love HACS; what it's become and what it promises for the future!  Just a suggestion.

**Comment by ludeeus** [comment]
Every line/card has an icon, the color and description (if you hold over it) of that icon tells you if an action is needed.

> (EDIT: It should also comply with the hiding feature! Same thing for the sensor alternative below.)

Hiding stuff you have installed makes no sense, that is why that feature is only applied on the store pages.

> a sensor that didn't just show the count, but provided a list of the names, installed versions and version available

It does that today.
![image](https://user-images.githubusercontent.com/15093472/68541079-6bb41680-039b-11ea-9b10-3173403587c0.png)

**Comment by rpitera** [comment]
> Every line/card has an icon, the color and description (if you hold over it) of that icon tells you if an action is needed.

C'mon, I'm well aware of the icons, Ludeeus.  But if you're showing the entire list of what is installed and the only thing that needs updating is "XYZ plugin" it's going to be at the bottom of the list and you're going to need to scroll to see it.  Right?

>Hiding stuff you have installed makes no sense, that is why that feature is only applied on the store pages.

The only reason I mentioned this is the case where there's a breaking change in something that prevents you from updating it until an upstream update is done.  I have this issue now with Feedparser.  The last update broke the List Card, so until Ian gets around to fixing it, I'm seeing a permanent update available.  I misunderstood how hiding works; there is no mention of it in the docs or FAQ.  Since it isn't explained, can I ask what is the reasoning behind it being applied in the store?  Again, I'm not being critical here for the sake of argument (you know me better) - I'd like to understand the function so I can use it for the right reasons.  I can't find any mention of the hiding feature in the docs so I don't know.  That's why I thought it was just a flag that was used to hide things you didn't want to see for whatever reason you might have.

>It does that today.

This is helpful.  And not knowing it was certainly my own fault; I've only checked the sensor on an entity card and never looked at the states panel.  And this would address my first question.  Do you have any ideas on how to display this as a list rather than how the sensor displays now?

![Untitled](https://user-images.githubusercontent.com/19910294/68546032-c308b580-03a0-11ea-8d00-1b916605bab1.jpg)

**Comment by rpitera** [comment]
I found the easiest way around my issue was to simply uninstall Feedparser from HACS and reinstall it manually.  That allows me to use the automation mentioned without modifying anything and retain the functionality (which addressed my two requests) and not get constant notifications for Feedparser.

I'd still like to understand the functionality/reasoning/use case behind the hiding feature and whenever you can get the time to answer, we can close this.  Thanks.

**Comment by ludeeus** [comment]
Have a look here:
<https://hacs.xyz/docs/navigation/settings#hidden-repositories>
<https://hacs.xyz/docs/navigation/repository#repository-menu>

**Comment by rpitera** [comment]
Well, that explains the how.  But I was looking for the 'why'.  See, you said:

> Hiding stuff you have installed makes no sense, that is why that feature is only applied on the store pages.

So I was looking to understand why hiding in the store _does_ make sense.  Maybe I am missing something obvious.  Maybe I am missing out on using a feature the way you intended it.  That's why I was asking; so I could learn.  I figure that if you put in code to do something, it must be important for some reason and since the reason I was intending to use it for wasn't the reason you had, I want to know so I'm not missing out on something useful.

**Comment by ludeeus** [comment]
Scenario:
You don't own any iOS devices, it does not make sense for you to see them in the store, you hide them.

You hide things you don't want to see.
If you have it installed, you certainly want to see it.

**Comment by rpitera** [comment]
>Scenario: You don't own any iOS devices, it does not make sense for you to see them in the store, you hide them.

Thanks, that was what I was looking for.  I am a mod in the HA forums and r/homeautomation as well as helping out in the HA subreddit.  I ask devs questions so I can help other people out.

I did have a use case to hide something that was installed **temporarily**, so that it didn't trigger an update notice every time in the notification example you gave,  but as I said I found a work around for it.  Once you hide something there is no way to unhide from what I can see.  So if you were to move from Android to iOS, the solution would be to uninstall and then reinstall?  It might make sense to add a warning to that effect in the docs you pointed to.

Thanks for taking the time to help me to understand.

**Comment by ludeeus** [comment]
If you look at the settings documentation link I send there are instructions to unhide as well ;)

**Comment by rpitera** [comment]
Oh, I just tried that and I'm not seeing the item I hid.  That's why I said that.

**Comment by ludeeus** [comment]
![unhide](https://user-images.githubusercontent.com/15093472/69015044-76207280-0990-11ea-8a93-84a411d25978.gif)

**Comment by rpitera** [comment]
I'm on 16.3 - is this in the update?
