### ISSUE TITLE
actionlink uses primary-color instead of primary-*text*-color

### ISSUE THREAD

**Issue by krissen** [hacs/frontend#17]
## Version of HACS
0.16.3

## Describe the bug
A minimalistic theme makes some HACS-buttons invisible.
<img width="1020" alt="Skärmklipp 2019-11-15 22 57 04" src="https://user-images.githubusercontent.com/2943684/68978766-feb9da00-07fb-11ea-9c7e-792879ae11e0.png">

(Yes, it sounds like it's a theming error. Might be. Let me explain further.)

So I might be wrong, but the `actionlink` element in `frontend/elements/hacs.css` uses `var(--primary-color)`. Shouldn't it be `var(--primary-text-color)`?

Though I'm new to theming, this is the only place so far where I've seen primary-color used for text.

**Comment by ludeeus** [comment]
It uses the same values as the rest of Home Assistant.
(like configuration -> Server control)

**Comment by krissen** [comment]
> It uses the same values as the rest of Home Assistant.
> (like configuration -> Server control)

Again, I'm a beginner at theming, but looking at configuration -> server control, I find no text which uses variable primary-color for coloring. I do find text which gets it's looks from mdc-theme-primary, primary-text-color, and mwc-button. 

<img width="664" alt="Skärmklipp 2019-11-16 21 37 24" src="https://user-images.githubusercontent.com/2943684/68999022-5159cb80-08ba-11ea-9c5c-84281eb6c48b.png">

Looking at a screenshot of said page, the banner at the top gets it's color from the variable primary-color but nothing else on the page does. 

Opening up details of a repository in HACS, however, not only is the banner-head (rightly) colored by `primary-color`, but also author's name and the buttons reinstall and repository.

<img width="648" alt="Skärmklipp 2019-11-16 21 53 40" src="https://user-images.githubusercontent.com/2943684/68999143-a3035580-08bc-11ea-9c82-e9a8b4d83f99.png">

If HACS would follow the way the page server control is built, the buttons might be mdc-theme-primary, and author's name would be primary-text-color, or some other text-color, if one would like to differentiate it from other text.

The only other place on HA, where I've thus far stumbled on text colored by primary-color, is the text for entity-names, in the list of entities at dev-state. [...] Yes, I'll open an issue about that over at HA-frontend, too, I think. I might be wrong, but so far I believe text shouldn't get it's color from primary-color -- but from primary-_text_-color (or the like). Been trying to find some kind of style-documentation to verify/falsify, but haven't found one yet.

**Comment by ludeeus** [comment]
Try again with 0.17.0
The file you are referencing does not exist.

**Comment by krissen** [comment]
Yes, looks as expected on 0.17.1! (Other visual things fixed also, I notice. Like for instance the spinner adhering to colors as expected, as opposed to versions prior to 0.17.) Great! Thanks.
