### ISSUE TITLE
Feature request: Sorting content by number of downloads

### ISSUE THREAD

**Issue by Ziqqo** [hacs/frontend#18]
# Describe the solution you'd like
Since the content of the store grows every day it is not really usable to browse the content to see if there is anything you might find useful. A sorting function to sort the contents for number of downloads would be really nice in order to find the popular projects. Listing downloads for latest release should be a good measurement of how popular it is, even though the numbers will go down for a while after a new release. There are probably more measurement that are relevant but I think this is a good start.

# Describe alternatives you've considered
At the moment there is not really a good alternative. I try to check into the forums for popular project sometimes but that does not provide a full picture.

# Additional context
download_count is accessible through the
GitHub API: https://developer.github.com/v3/repos/releases/
A specific release can be fetched by 
GET /repos/:owner/:repo/releases/:release_id

**Comment by ludeeus** [comment]
Currently this would only apply to 1% of the repositories.
This kind of sorting will not give the user any value, and will not be fair to the developer that do not have release assets.
