### ISSUE TITLE
Integration shown as not loaded but it is

### ISSUE THREAD

**Issue by DavidFW1960** [hacs/frontend#21]
## Version of HACS
17.1

## Describe the bug
iPhone tracker showing with a red icon. It is loaded in config and it's working. Just hacs shows red icon. It is up to date too.

## Debug log

```text
There is no error as such. 
Add your logs here.

```

**Comment by ludeeus** [comment]
Fixed in 0.17.2

**Comment by DavidFW1960** [comment]
Not sure how this got derailed into being a plugin issue!!! It is nothing to do with lovelace - it was an integration not showing.. a custom_component so lovelace config not relevant.

In any case it's fixed in 0.17.2 as Ludeeus said.

When HA restarted after installing it, lots showed red until HACS finished updating then everything was fine.
