### ISSUE TITLE
HACS theme variables

### ISSUE THREAD

**Issue by hekm77** [hacs/frontend#22]
## Version of HACS

17.3

## Describe the bug
HACS theme variables do not work since 17.x
The variables worked fine on version 16.3

```
hacs-badge-color: "#2980B9"
hacs-badge-text-color: "#FFFFFF"
hacs-status-installed: "#39E949"
hacs-status-pending-restart: "#E45E65"
hacs-status-pending-update: "#FFA73B"
```

## Debug log

```text


```

**Comment by ludeeus** [comment]
Fixed with https://github.com/hacs/frontend/commit/9734dedee169c3d859dfc45e79f32372a7ef31fb will be part of the next release.
Also added in `hacs-status-not-loaded`

**Comment by hekm77** [comment]
Same problem on the 0.18.2
