### ISSUE TITLE
Display Github stars as a measure of popularity

### ISSUE THREAD

**Issue by basnijholt** [hacs/frontend#28]
There is a massive amount of plugins and integrations (and more) in the community store.

Some of them might just be gimmicks and some are super useful packages that a lot of people use.

Right now there is no way of finding out which repos are the popular and frequently used ones, and which ones aren't.

I think it would be great if the plugins would display the amount of Github stars ⭐️ inside the overview of installable repos as a measure of popularity.

An alternative is to display the number of installs, but that would require keeping track of this in a database.

**Comment by basnijholt** [comment]
I see you transferred the issue and added a "help wanted" tag.

Unfortunately, I cannot help you with typescript at all 😢

What do you think of the idea though?

**Comment by ludeeus** [comment]
Not sure yet, the metric is there <https://github.com/hacs/frontend/commit/e091b21d5b31986d2e59deeabf12519ceed1717d>
But it has not been indexed so everything you have not installed will have a value of 0.

Not sure what this gives that the "Repository" button does not.

**Comment by basnijholt** [comment]
I would like to sort on the number of stars. In a way, it is like app reviews, like in the Google Play store or App Store.

Of course, you can see it inside the repository, but I would like to see it before I even click on the name.

**Comment by ludeeus** [comment]
> But it has not been indexed so everything you have not installed will have a value of 0.

95% with 0, is not that good of an indication.
It is there now, and in the master of the backend.

_maybe_ sometime in the future, it can be utilized.

As for sorting, there is a PR "ready" that will add that #23

**Comment by basnijholt** [comment]
Oh sweet! Would one be able to sort on stars?

**Comment by ludeeus** [comment]
> maybe sometime in the future, it can be utilized.

**Comment by basnijholt** [comment]
> 95% with 0, is not that good of an indication.

That is just a matter of time I guess.

**Comment by ludeeus** [comment]
As a first step, I will not add the star counter itself, since folks are slow to update their HACS installation the dataset would not be complete.

I'm adding that as a task to implement before 1.0

As for now I added an option to sort by stars <https://github.com/hacs/frontend/commit/4ce9665a9bc8ce0ec047d7e3804a6af166b920da>

**Comment by basnijholt** [comment]
That's great!

This will make it to the next release I suppose?

**Comment by ludeeus** [comment]
Yeah, it will be in 0.19.0.
But that is not planed until sometime next year, I need to rework a lot of the frontend to make it more modular (and simpler) then what it is right now.

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/71173976-5799e980-2264-11ea-9bba-25f63ec038a0.png)
I have tried various ways of displaying it in the overviews, but it did not look any good.
Has added it to the repository views, as well as added a download counter if the repository uses release assets.

This is the most I'm willing to do to achieve this request.

**Comment by basnijholt** [comment]
This is definitely all I could wish for!

Sorting on the number of stars is the most useful (I think).
