### ISSUE TITLE
Add Czech language to lokalise

### ISSUE THREAD

**Issue by kukulich** [hacs/frontend#303]
Please :)

**Comment by KTibow** [comment]
Are you willing to help out? You need someone to volunteer to help out. You can create a draft PR, and people can help out.

**Comment by kukulich** [comment]
@KTibow I don’t understand. Czech is missing in localise application so I cannot translate.

**Comment by KTibow** [comment]
Sorry, don't know any other languages or how to use localise. Can you manually make the file?

**Comment by kukulich** [comment]
I just open the issue as others before: https://github.com/hacs/frontend/issues/118

**Comment by ludeeus** [comment]
"Czech" does not exist in lokalise

**Comment by kukulich** [comment]
I still don't see Czech in lokalise :( Did I something wrong?

**Comment by ludeeus** [comment]
It does not exist in lokalise, so it can not be added.

**Comment by kukulich** [comment]
@ludeeus I don't understand. It's in HA frontend, core and companion application.

**Comment by kukulich** [comment]
![Clipboard01](https://user-images.githubusercontent.com/260445/99155947-0b963580-26bd-11eb-9f20-c0b4e9d544b7.png)

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/99155967-3aaca700-26bd-11eb-8975-f05997636431.png)

**Comment by kukulich** [comment]
`cs` maybe? It's Czech but the ISO code is `cs`.

**Comment by ludeeus** [comment]
`cs` added <https://app.lokalise.com/project/854515055f679055040b37.42677693/?view=single&reference_lang_id=640&single_lang_id=765>

**Comment by kukulich** [comment]
Perfect, thank you.
