### ISSUE TITLE
Unable to add custom repo

### ISSUE THREAD

**Issue by freemann** [hacs/frontend#31]
I'm using some custom repo's and wanted to add one today, but the save button isn't working.
First the "?" is in the way and after I deleted at through Chrome developers panel, the "save" button isn't working.

I see no console errors and/or network traffic after hitting the save button.
![Screenshot - 25_11_2019 , 11_41_34](https://user-images.githubusercontent.com/601053/69533690-8fb94f80-0f78-11ea-92e0-0b6d7a6d6543.png)

**Comment by ludeeus** [comment]
If no console error, look for error in your HA log

**Comment by freemann** [comment]
![Screenshot - 25_11_2019 , 11_44_13](https://user-images.githubusercontent.com/601053/69533845-e9217e80-0f78-11ea-8859-ddf2c42de3d8.png)
Ah ok....

Maybe you can give some feedback in the HACS frontend?

The issue is clear to me, so closing it :) Thanks for you quick response!
