### ISSUE TITLE
restart pending visible as white on white

### ISSUE THREAD

**Issue by HABuild** [hacs/frontend#35]
When I install or update integrations the resultant restart required message is coming up white on white. I use the stock backend selected hassio theme, and have no themes installed. browser reload and cache clear give no change. 
Hassio 102.2 
HACs 0.17.4
Chrome browser 78.0.3904.108

The view when integration installed
![hacs whiteonwhite](https://user-images.githubusercontent.com/36288425/70002819-535ba400-15b5-11ea-854e-22c1e4310270.PNG)

Text selected version
![hacs highlighted](https://user-images.githubusercontent.com/36288425/70002825-56ef2b00-15b5-11ea-9f1a-961526f0fe92.PNG)

**Comment by ludeeus** [comment]
Fixed in master
