### ISSUE TITLE
Help button link in HA goes to blank page

### ISSUE THREAD

**Issue by safepay** [hacs/frontend#36]
When clicking on the orange help icon in Home Assistant the link opens a blank page with HACS headers.

The line in frontend/src/buttons/HacsHelpButton.ts:

        const base = "https://hacs.xyz/docs/navigation/"

needs to be changed to:

        const base = "https://hacs.xyz/docs/basic/getting_started/"

**Comment by ludeeus** [comment]
Where?

**Comment by safepay** [comment]
The big orange question mark in the bottom right corner.

**Comment by ludeeus** [comment]
Yeah...
But from where are you getting a blank page?
Every part I have tested works

**Comment by safepay** [comment]
Here is the page the link opens in Chrome:
![Annotation 2019-12-16 073957](https://user-images.githubusercontent.com/31983230/70868704-66b83780-1fd7-11ea-989d-e48e9e4f9d78.png)

**Comment by ludeeus** [comment]
But from **where** are you getting a blank page?

**Comment by safepay** [comment]
This sounds like semantics.

Under the headers there is no text, therefore to a user looking for help, there is no clear action.

**Comment by ludeeus** [comment]
Fine... don't provide info..
I'll just assume your browser is broken.

On my setup, it takes me to:
<https://hacs.xyz/docs/navigation/settings>
<https://hacs.xyz/docs/navigation/stores>
<https://hacs.xyz/docs/navigation/repository>
and
<https://hacs.xyz/docs/navigation/installed>
Depending on where I am when I click it.

**Comment by safepay** [comment]
No need to be like that. I'm trying to help.
That screenshot with no information, just headings, is the same on Firefox and Chrome on Windows.

I am saying that the issue is that headings only and a blank page is not useful for people. There should be text under the headings.

There s a brief flash of a 404 error in the blank area on FireFox showing that there should be content but that it is missing.

Maybe I'm wrong and the original intent was to only have headings. If so, then I apologise for any confusion.

**Comment by ludeeus** [comment]
The URL is generated from the page **in HACS** you are on when you click the ? button.
