### ISSUE TITLE
Missing s

### ISSUE THREAD

**Issue by isabellaalstrom** [hacs/frontend#42]
https://github.com/hacs/frontend/blob/4fdc3c6317cda6ad64bb13d3a30b5ab85ef2a939/src/localize/localize.ts#L49
![image](https://user-images.githubusercontent.com/22006797/71091140-dc253300-21a4-11ea-99c9-82cdb8584728.png)

**Comment by ludeeus** [comment]
Who cares 😂 
Feel free to correct it in a PR.

**Comment by isabellaalstrom** [comment]
LOL :D
