### ISSUE TITLE
Reloading data seems to take forever

### ISSUE THREAD

**Issue by JoshuaMulliken** [hacs/frontend#43]
When I click the Reload Data button in the settings tab the thing begins to spin and never finishes. I have to restart HA to get it to stop.

**Comment by ludeeus** [comment]
No you don't, you can just refresh the page

**Comment by JoshuaMulliken** [comment]
I did refresh the page and it is still going @ludeeus

**Comment by ludeeus** [comment]
Then it's probably still working, it can take hours

**Comment by JoshuaMulliken** [comment]
Can I set something in my logger config so I can check the progress?

**Comment by ludeeus** [comment]
https://hacs.xyz/docs/basic/logs

**Comment by JoshuaMulliken** [comment]
Great thank you! I can see each one working.
