### ISSUE TITLE
Sort by creation date / last update

### ISSUE THREAD

**Issue by woody4165** [hacs/frontend#46]
**Is your feature request related to a problem? Please describe.**
Feature request not related to a problem.

**Describe the solution you'd like**
Is it possible to add a sort by creation date / last update for all the components?
This should be in the Integrations, Plugins, Python Scripts and Theme tabs.

Thanks

**Describe alternatives you've considered**
No alternative to be considered.

**Additional context**
None

**Comment by ludeeus** [comment]
Added sort by `last_updated`
