### ISSUE TITLE
Add Hebrew translation

### ISSUE THREAD

**Issue by tzagim** [hacs/frontend#492]
After I translated everything into Hebrew, I noticed that you use lokalise.com for translation, I would love to add Hebrew.

#491

**Comment by ludeeus** [comment]
Is that `he` or `he_IL`?

**Comment by tzagim** [comment]
`he`.

`lang_id=766` in lokalise.com

**Comment by ludeeus** [comment]
https://app.lokalise.com/project/854515055f679055040b37.42677693/?view=single&reference_lang_id=640&single_lang_id=766

**Comment by tzagim** [comment]
> 
> 
> https://app.lokalise.com/project/854515055f679055040b37.42677693/?view=single&reference_lang_id=640&single_lang_id=766

Does not show me the Hebrew language.

Need to wait?

**Comment by ludeeus** [comment]
You choose which languages you want to see with your user, when a new lang is added you have to enable that for your user.
No, files can't be imported with the way we use it, that will replace all existing keys for all languages

**Comment by tzagim** [comment]
I can not see it, I spoke twice with their support and they say it is something that should be done in the Admin interface.
Or maybe you can guide me on how to do it? Thanks in advance

**Comment by ludeeus** [comment]
What username?

**Comment by tzagim** [comment]
> 
> 
> What username?

tzag tirgum

**Comment by ludeeus** [comment]
should be added now

**Comment by ludeeus** [comment]
It still needs to be added in the UI (I think)

**Comment by tzagim** [comment]
It appeared to me as soon as you wrote.
I finished translating :)
