### ISSUE TITLE
scroll position lost when returning from integration / plugin

### ISSUE THREAD

**Issue by quazzie** [hacs/frontend#5]
**Is your feature request related to a problem? Please describe.**
Scroll position is lost when clicking on an integration/plugin and returning back.

**Describe the solution you'd like**
Restore scroll position when going back to to ex. store page.

**Describe alternatives you've considered**
Tried opening plugins in new tab but that does not work.

**Comment by ludeeus** [comment]
Without doing calculations and/or storing this kind of things as cookies, I think the current state of the experimental UI and how that operates are as good as this can be.

I will not be pursuing this anymore now.
