### ISSUE TITLE
Table view erroneously shows 'New'

### ISSUE THREAD

**Issue by MatthewFlamm** [hacs/frontend#50]
## Version of HACS
0.19.0

## Describe the bug
Without table view, there are no new indicators for any repository after I 'clear' it using the button.  But if I turn on table view, the icon next to each item becomes new.  It is like this on each tab in HACS.

![Screenshot_20191221-090317](https://user-images.githubusercontent.com/39341281/71309012-022f1b00-23d1-11ea-86ce-7cf72e98e86f.png)

## Debug log
None

**Comment by ludeeus** [comment]
Has already been fixed https://github.com/hacs/frontend/commit/394eeb53bd1a8690dad38988dfbd8ab1e5eaa89b

**Comment by MatthewFlamm** [comment]
I hope I didn't duplicate an existing issue, I did search but didn't find anything.  Thanks for all your wonderful work!

**Comment by ludeeus** [comment]
Nope, no one else has reported it
