### ISSUE TITLE
Spacing needed between switches in Settings

### ISSUE THREAD

**Issue by bonanitech** [hacs/frontend#51]
I think some spacing is needed between the switches in Settings. I was trying to enable/disable `Table view` but was toggling `Compact mode` because the switches' clickable/tappable area overlaps each other.

![Screen Shot 2019-12-22 at 8 03 20 AM](https://user-images.githubusercontent.com/29807944/71322162-990fdc00-2492-11ea-9354-1ca10539b3de.png)

**Comment by ludeeus** [comment]
Those are removed in the master, replaced with this:
![sdsdjadsa](https://user-images.githubusercontent.com/15093472/71322308-93cc8480-24c6-11ea-8453-74e14cd9b170.gif)

**Comment by bonanitech** [comment]
Dude, you are on fire! One amazing update after another.

Thanks for the feedback and happy holidays.
