### ISSUE TITLE
Translation problem with 'repository.note_downloaded'?

### ISSUE THREAD

**Issue by lulee007** [hacs/frontend#547]
chrome console log error:
```
 [HACS.localize] Translation problem with 'repository.note_downloaded' for 'zh_Hans'
```
https://github.com/hacs/frontend/blob/970dc1ce09eb7b26eba4cdef9521da326868bc89/src/components/dialogs/hacs-download-dialog.ts#L155

https://github.com/hacs/frontend/commit/970dc1ce09eb7b26eba4cdef9521da326868bc89#diff-12d32693d296e25fbdd26131c267fc760fdb6dc1f558b4e426b97fab9e1f82a1L92
```
"note_installed": "When downloaded, this will be located in",
```

`note_downloaded` means `note_installed`?

**Comment by emufan** [comment]
@ludeeus Hi Joakim. I have the same error showing (german). Translation is available in js-file. But I didn't see a solution or explanation, only that this issue has been closed directly. Is there a fix for that, for which I have to wait or which I have to do?

**Comment by ludeeus** [comment]
Issue was not opened in the proper place
and yes, wait.
