### ISSUE TITLE
add restart button 

### ISSUE THREAD

**Issue by adonno** [hacs/frontend#57]
whenever an integration is updated or installed, we get a restart pending notification 

why not add a "restart" button here?  

![image](https://user-images.githubusercontent.com/13216947/71535318-3f316b00-2905-11ea-8b92-9ae395a4a1c6.png)

**Comment by ludeeus** [comment]
![image](https://user-images.githubusercontent.com/15093472/71547565-f380cf00-29a1-11ea-94f8-b7e9d19536f8.png)
***
![image](https://user-images.githubusercontent.com/15093472/71547568-fb407380-29a1-11ea-88e7-865a571fe87e.png)
***
Added with <https://github.com/hacs/frontend/commit/596c53d4160a4967c5e137ae9d0fe593b21ad3c0>
