### ISSUE TITLE
"Last Updated" display issues

### ISSUE THREAD

**Issue by MarcJenningsUK** [hacs/frontend#59]
## Version of HACS
0.20.4

## Describe the bug
For all listed items under each category, the "Last Updated" filed shows dupolicate numeric values
eg: expected result -- Last updated: 20 hours ago
actual result -- Last updated: 20 20 hours ago

## Debug log

n/a

**Comment by ludeeus** [comment]
Fixed with https://github.com/hacs/frontend/commit/fc1a5a2509dd52773d0aaf34d89355967650f1e7
