### ISSUE TITLE
The window "CUSTOM REPOSITORIES" blinks all the time

### ISSUE THREAD

**Issue by conrad66** [hacs/frontend#60]
HASS version: 0.103.5
HACS Version: 0.20.4
The window SETTINGS / "CUSTOM REPOSITORIES" blinks all the time
![2019-12-29_17-09-52](https://user-images.githubusercontent.com/5843698/71557913-153f8c00-2a5e-11ea-984e-1534bd01509a.png)
https://youtu.be/8KKD85MUy-g

**Comment by ludeeus** [comment]
Duplicate of #58
