### ISSUE TITLE
listicon and saveicon should not use primary-color

### ISSUE THREAD

**Issue by krissen** [hacs/frontend#61]
I'm not entirely sure if this is a HACS issue, polymer, or homeassistant, but so far only stumbled on `saveicon` and `listicon` elements in HACS, so submitting an issue here. (Also; already tried at [ha-polymer](https://github.com/home-assistant/home-assistant-polymer/issues/4394).)

HACS uses elements `saveicon` and `listicon` and they are coloured via `primary-color`. I'd like to suggest they should not, but rather by `paper-item-icon` or some such? Text-color (primary or secondary) would also be an option, as would accent-color -- but not primary. In a minimalistic theme, it leads to the icons in effect being invisible.

**Comment by ludeeus** [comment]
They will be `hacs-badge-color` in the next version
