### ISSUE TITLE
Add ability to configure Tabs after installation.

### ISSUE THREAD

**Issue by Petro31** [hacs/frontend#67]
I never checked 'python scripts' as a tab when installing.  I'd like to add that tab and it's items via the configuration menu.

I envision the options in the integration page containing checkboxes for each tab.  Checked = tab is visible w/ contained items.

**Comment by ludeeus** [comment]
That setting is no longer used.
https://hacs.xyz/docs/categories/python_scripts#enable-python-scripts-in-home-assistant

**Comment by Petro31** [comment]
Ah, my mistake.
