### ISSUE TITLE
After beeing in HACS the first more-info of HA reloads UI

### ISSUE THREAD

**Issue by VDRainer** [hacs/frontend#72]
I first opened an issue in the HA frontend https://github.com/home-assistant/home-assistant-polymer/issues/4792, but now i think i found the culprit.
After beeing in HACS, the first more-info dialog that is opened and closed, reloads the HA UI as if you press CTRL-F5 in your browser.
This happens even after hours leaving the HACS panel, and so it was very hard to find.
![hacs_issue](https://user-images.githubusercontent.com/26381449/74030105-81db6e00-49ae-11ea-962d-e9d4e15f708c.gif)

**Comment by ludeeus** [comment]
That SUCKS!
