### ISSUE TITLE
"Unsupported HomeAssistant Version" message don't mach the desired version to install

### ISSUE THREAD

**Issue by GuyKh** [hacs/frontend#8]
## Describe the bug
An error with the `Unsupported HomeAssistant Version` - when selecting a different version to install than the default and (maybe) both don't match the HomeAssistant version, the plugin version used is not the right one.

## Example
Here you see I selected the version `master` (default was 1.0.1) - but the message is describing version 1.0.1 which is not selected
![Example](https://i.imgur.com/KktzMC6.jpg)

**Comment by ludeeus** [comment]
This is now handled and will be part of the next release.
https://github.com/hacs/frontend/commit/f121f627e2873327338875d195f9fb9f1e9143ef
