### ISSUE TITLE
Corrupted Content Error

### ISSUE THREAD

**Issue by tiagofreire-pt** [hacs/frontend#81]
After installing the version 0.22.0, my HA instance crashes the lovelace interface, giving "Corrupted Content Error" on Firefox and the android companion app "ERR_FAILED".

I have to restart the entire instance to access it again successfully. 

No errors are stated on HA logs or on the supervisor.

**Comment by ludeeus** [comment]
The Lovelace panel is not a part of HACS.
And without logs there is nothing I can do.

**Comment by tiagofreire-pt** [comment]
Solved by doing a fresh HA install, recurring to its own full backups.
