### ISSUE TITLE
Add to Lovelace button does not work from Firefox 68.5.0esr

### ISSUE THREAD

**Issue by jasonblewis** [hacs/frontend#83]
When I install a plugin, after HA reloads it says the plugin is not loaded into lovelace.
When I hit the Add to Lovelace button, the page reloads but it still says the plugin is not loaded, and has the button to add to lovelace. I've enabled hacs debugging logs and all I see is this in the logs:
`2020-03-12 10:18:26 INFO (MainThread) [homeassistant.components.websocket_api.http.connection.1583454064] Connection closed by client`

I tested from Chrome and that does work.

Tested in HACS .23.2 and problem still exists.

Let me know if you need any other info

**Comment by ludeeus** [comment]
Check your browser console logs.

**Comment by ludeeus** [comment]
I can not replecate with 68.6.1esr (64-bit).
Might have been fixed in FF or HACS 🤷‍♂
