### ISSUE TITLE
HACS freezes after clicking settings

### ISSUE THREAD

**Issue by mrdjdevil** [hacs/frontend#84]
Hi, I'm having some issues with HACS. When I click "settings" the entire tab freezes, which can be seen in the Chrome task manager. CPU goes to 100% 

https://www.loom.com/share/9034c972fd5d4f6690094246d99b7754

**Comment by ludeeus** [comment]
You know that link is from installed tab?

What does HA logs say?
What is printed to the browser console?
What version of chrome do you use?
