### ISSUE TITLE
HACS does not detect plugin in Lovelace if there is versioning in the file

### ISSUE THREAD

**Issue by gerardo15** [hacs/frontend#86]
Hello,

When i add the resources to the lovelace i tend to add it with versioning at the end of the file as following 

url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js?v=1

So when the file updates it does not cache in mobile and web.

But when i add the version the following shows

![image](https://user-images.githubusercontent.com/12488663/77121894-8fb7f080-6a3c-11ea-89ff-dd2a62a72077.png)

I think the comparation wether the file is in resources or not should be doing removing the get parameters from the url.

**Comment by ludeeus** [comment]
That is expected, don't do that.
/hacsfiles/ are without cache already https://hacs.xyz/docs/categories/plugins#custom-view-hacsfiles
